version: 2.1

commands:
  install-deps:
    description: Install dependencies using pre-commit
    steps:
      - command: |
          pip install pre-commit tox flit
          pre-commit install

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - install-deps
      - run: tox
  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - install-deps
      - command: |
          FLIT_USERNAME=narrativescience FLIT_PASSWORD=$PYPI_PASSWORD flit publish

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
