version: 2.1

orbs:
  ghpr: narrativescience/ghpr@0.0.5

commands:
  install-deps:
    description: Install dependencies and initialize pre-commit hooks
    steps:
      - run:
          command: |
            pip install pre-commit tox flit
            pre-commit install
          name: Install dependencies

jobs:
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - ghpr/build-prospective-branch
      - install-deps
      - run: pre-commit run --show-diff-on-failure
      - run: tox
      - run: flit build
      - ghpr/post-pr-comment:
          comment: Tests failed!
          when: on_fail
  publish:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: pip install flit
      - run: flit build
      - run: flit publish

workflows:
  pull_request:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
  publish:
    jobs:
      - publish:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
