version: 2.1

jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |
            pip install pre-commit tox
            pre-commit install
          name: Install Requirements
      - run: tox

workflows:
  main:
    jobs:
      - build_and_test
