version: 2.1

orbs:
  ghpr: narrativescience/ghpr@0.0.5

commands:
  install-deps:
    description: Install dependencies and initialize pre-commit hooks
    steps:
      - run:
          command: |
            pip install pre-commit tox flit
            pre-commit install
          name: Install dependencies
  get-target-branch:
    # This is a workaround until CircleCI implements a feature for exposing the
    # target branch of a pull request. See https://ideas.circleci.com/ideas/CCI-I-894
    # for more information.
    description: Get target branch
    steps:
      - run:
          name: Get target branch
          command: |
            url="https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pulls/${PR_NUMBER}"
            target_branch=$(curl --user "${GITHUB_USERNAME}:${GITHUB_PASSWORD}" "$url" | jq '.base.ref' | tr -d '"')
            echo "$target_branch"
            echo "export TARGET_BRANCH=$target_branch" >> $BASH_ENV

jobs:
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - ghpr/build-prospective-branch
      - get-target-branch
      - install-deps
      - run:
          name: Run commit hooks
          command: |
            pre-commit run \
              --source "origin/${TARGET_BRANCH}" \
              --origin "origin/${CIRCLE_BRANCH}" \
              --show-diff-on-failure
      - run: tox
      - run: flit build
      - ghpr/post-pr-comment:
          comment: Tests failed!
          when: on_fail
  publish:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: pip install flit
      - run: flit build
      - run: flit publish

workflows:
  pull_request:
    jobs:
      - test
  publish:
    jobs:
      - publish:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
