version: 2.1

commands:
  install-deps:
    description: Install dependencies using pre-commit
    steps:
      - run:
          command: |
            pip install pre-commit tox flit
            pre-commit install
          name: Install dependencies

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - install-deps
      - run: tox
  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |
            FLIT_USERNAME=$PYPI_USERNAME FLIT_PASSWORD=$PYPI_PASSWORD flit publish
          name: Publish to Pypi

workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
